import { Tool } from "@modelcontextprotocol/sdk/types.js";

export const TOOLS: Tool[] = [
  {
    name: "list_endpoints",
    description:
      "STEP 1 (EXPLORATION): List all available endpoints. ALWAYS use this first to understand the API capabilities and available routes before developing any feature.",
    inputSchema: {
      type: "object",
      properties: {
        limit: {
          type: "number",
          description: "Limit the number of results (default: 50).",
        },
        offset: {
          type: "number",
          description: "Starting index for pagination (default: 0).",
        },
      },
    },
  },
  {
    name: "get_endpoint_info",
    description:
      "STEP 2 (ANALYSIS): Get full technical details of a specific endpoint, including required parameters, headers, and response structure. Use this before writing any code.",
    inputSchema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "The endpoint path (e.g., '/api/v1/users')",
        },
        method: {
          type: "string",
          description: "HTTP method (GET, POST, etc.)",
        },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "get_typescript_types",
    description:
      "FRONTEND (TYPING): Generate TypeScript interfaces for request bodies and response data. Essential for maintaining type safety in frontend development.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "get_zod_schema",
    description:
      "FRONTEND (VALIDATION): Generate Zod validation schemas for request or response bodies. Perfect for implementing form validation that matches backend rules.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
        target: {
          type: "string",
          enum: ["request", "response"],
          description: "Validation target (default: 'request')",
        },
        statusCode: {
          type: "string",
          description: "HTTP status code for response validation (default: '200')",
        },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "get_framework_snippet",
    description:
      "FRONTEND (IMPLEMENTATION): Generate complete code snippets for modern frameworks like Axios or TanStack Query, including error handling and types.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
        framework: {
          type: "string",
          enum: ["axios", "tanstack-query"],
          description: "Target framework",
        },
      },
      required: ["path", "method", "framework"],
    },
  },
  {
    name: "validate_response",
    description:
      "BACKEND (TESTING): Validate a JSON object against the OpenAPI response schema. ALWAYS use this after writing backend code to verify your implementation matches the contract.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
        statusCode: {
          type: "string",
          description: "Expected HTTP status code (default: '200')",
        },
        data: {
          type: "object",
          description: "The JSON response object generated by your code to be validated.",
        },
      },
      required: ["path", "method", "data"],
    },
  },
  {
    name: "get_mock_data",
    description:
      "FRONTEND (PROTOTYPING): Generate high-fidelity mock data that satisfies the OpenAPI schema. Use this to test UI components before the backend is fully ready.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "find_endpoint",
    description:
      "SEARCH: Find endpoints by intent or keyword (e.g., 'delete user', 'upload file'). Useful when you know what you want to do but not the exact route.",
    inputSchema: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "Search term or user intent.",
        },
      },
      required: ["query"],
    },
  },
  {
    name: "map_dependencies",
    description:
      "ARCHITECTURE: Analyze ID relationships between endpoints. Use this to understand the data flow and which endpoint provides the ID required by another.",
    inputSchema: {
      type: "object",
      properties: {
        resourceName: {
          type: "string",
          description: "Optional: Filter by resource name (e.g., 'user', 'album').",
        },
      },
    },
  },
  {
    name: "search_by_tag",
    description: "Search for endpoints by tag.",
    inputSchema: {
      type: "object",
      properties: {
        tag: {
          type: "string",
          description: "The tag to search for.",
        },
      },
      required: ["tag"],
    },
  },
  {
    name: "get_request_schema",
    description: "Get the JSON request body schema for an endpoint.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "get_response_schema",
    description: "Get the JSON response body schema for an endpoint.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
        statusCode: {
          type: "string",
          description: "HTTP status code (default: '200')",
        },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "list_tags",
    description: "List all tags available in the OpenAPI specification.",
    inputSchema: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_fetch_snippet",
    description: "Generate a fetch code snippet for an endpoint.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
      },
      required: ["path", "method"],
    },
  },
  {
    name: "get_security_info",
    description: "Get security requirements for the API or a specific endpoint.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
      },
    },
  },
  {
    name: "set_security_context",
    description: "Set authentication headers to be used for subsequent 'call_endpoint' requests.",
    inputSchema: {
      type: "object",
      properties: {
        headers: {
          type: "object",
          description: "Headers to include (e.g., { 'Authorization': 'Bearer ...' })",
        },
        scope: {
          type: "string",
          description: "Optional scope for these headers (e.g., 'global' or a specific tag).",
        },
      },
      required: ["headers"],
    },
  },
  {
    name: "call_endpoint",
    description:
      "DEBUG: Execute a real HTTP request to the configured API to verify live behavior and connectivity.",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string" },
        method: { type: "string" },
        parameters: {
          type: "object",
          description: "Path and query parameters.",
        },
        body: { type: "object", description: "JSON request body." },
        headers: { type: "object", description: "Additional HTTP headers." },
      },
      required: ["path", "method"],
    },
  },
];
